apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    application-crd-id: data-science-pipelines
  annotations:
    serviceaccounts.openshift.io/oauth-redirectreference.primary: '{"kind":"OAuthRedirectReference","apiVersion":"v1","reference":{"kind":"Route","name":"ds-pipeline-ui"}}'
  name: ds-pipeline-ui
