apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    opendatahub.io/notebook-image: "true"
  annotations:
    opendatahub.io/notebook-image-url: "https://github.com/opendatahub-io/notebooks/tree/main/jupyter/minimal/ubi8-python-3.8"
    opendatahub.io/notebook-image-name: "CUDA"
    opendatahub.io/notebook-image-desc: "Jupyter notebook image with GPU support and minimal dependency set to start experimenting with Jupyter environment."
    opendatahub.io/notebook-image-order: "3"
  name: jupyter-minimal-gpu-notebook
spec:
  lookupPolicy:
    local: true
  tags:
  - annotations:
        opendatahub.io/notebook-software: '[{"name":"Python","version":"v3.8"}]'
        opendatahub.io/notebook-python-dependencies: '[{"name":"JupyterLab","version":"3.2"},{"name":"Notebook","version":"6.4"}]'
        openshift.io/imported-from: quay.io/opendatahub/notebooks
    from:
      kind: DockerImage
      name: quay.io/opendatahub/notebooks@sha256:c13cd3410e31184986d44d36ba663ca2f2225d14e5b086b09fe221219a94b6de
    name: "py3.8-v1"
    referencePolicy:
      type: Local
