apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ds-pipeline-visualizationserver
    application-crd-id: data-science-pipelines
  name: ds-pipeline-visualizationserver
spec:
  selector:
    matchLabels:
      app: ds-pipeline-visualizationserver
      application-crd-id: data-science-pipelines
  template:
    metadata:
      annotations:
        cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
      labels:
        app: ds-pipeline-visualizationserver
        application-crd-id: data-science-pipelines
    spec:
      containers:
        - image: visualization-server
          imagePullPolicy: Always
          name: ds-pipeline-visualizationserver
          ports:
            - containerPort: 8888
              name: http
          livenessProbe:
            exec:
              command:
                - wget
                - -q
                - -S
                - -O
                - '-'
                - http://localhost:8888/
            initialDelaySeconds: 30
            periodSeconds: 5
            timeoutSeconds: 2
          readinessProbe:
            exec:
              command:
                - wget
                - -q
                - -S
                - -O
                - '-'
                - http://localhost:8888/
            initialDelaySeconds: 3
            periodSeconds: 5
            timeoutSeconds: 2
          resources:
            requests:
              cpu: 30m
              memory: 500Mi
            limits:
              cpu: 250m
              memory: 1Gi
      serviceAccountName: ds-pipeline-visualizationserver
