apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ds-pipeline
    application-crd-id: data-science-pipelines
  name: ds-pipeline
spec:
  selector:
    matchLabels:
      app: ds-pipeline
      application-crd-id: data-science-pipelines
  template:
    metadata:
      annotations:
        cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
      labels:
        app: ds-pipeline
        application-crd-id: data-science-pipelines
    spec:
      containers:
        - envFrom:
            - secretRef:
                name: $(artifact_secret_name)
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: DBCONFIG_USER
              valueFrom:
                secretKeyRef:
                  key: username
                  name: $(database_secret)
            - name: DBCONFIG_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: $(database_secret)
            - name: DBCONFIG_DBNAME
              valueFrom:
                configMapKeyRef:
                  key: pipelineDb
                  name: $(pipeline_install_configuration)
            - name: DBCONFIG_HOST
              valueFrom:
                configMapKeyRef:
                  key: dbHost
                  name: $(pipeline_install_configuration)
            - name: DBCONFIG_PORT
              valueFrom:
                configMapKeyRef:
                  key: dbPort
                  name: $(pipeline_install_configuration)
            - name: PIPELINE_RUNTIME
              value: tekton
            - name: ARTIFACT_BUCKET
              valueFrom:
                configMapKeyRef:
                  key: artifact_bucket
                  name: $(ds_pipelines_configuration)
            - name: ARTIFACT_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  key: artifact_endpoint
                  name: $(ds_pipelines_configuration)
            - name: ARTIFACT_ENDPOINT_SCHEME
              valueFrom:
                configMapKeyRef:
                  key: artifact_endpoint_scheme
                  name: $(ds_pipelines_configuration)
            - name: ARCHIVE_LOGS
              valueFrom:
                configMapKeyRef:
                  key: archive_logs
                  name: $(ds_pipelines_configuration)
            - name: TRACK_ARTIFACTS
              valueFrom:
                configMapKeyRef:
                  key: track_artifacts
                  name: $(ds_pipelines_configuration)
            - name: STRIP_EOF
              valueFrom:
                configMapKeyRef:
                  key: strip_eof
                  name: $(ds_pipelines_configuration)
            - name: ARTIFACT_SCRIPT
              valueFrom:
                configMapKeyRef:
                  key: artifact_script
                  name: $(ds_pipelines_configuration)
            - name: ARTIFACT_IMAGE
              valueFrom:
                configMapKeyRef:
                  key: artifact_image
                  name: $(ds_pipelines_configuration)
            - name: INJECT_DEFAULT_SCRIPT
              valueFrom:
                configMapKeyRef:
                  key: inject_default_script
                  name: $(ds_pipelines_configuration)
            - name: APPLY_TEKTON_CUSTOM_RESOURCE
              valueFrom:
                configMapKeyRef:
                  key: apply_tekton_custom_resource
                  name: $(ds_pipelines_configuration)
            - name: TERMINATE_STATUS
              valueFrom:
                configMapKeyRef:
                  key: terminate_status
                  name: $(ds_pipelines_configuration)
            - name: AUTO_UPDATE_PIPELINE_DEFAULT_VERSION
              valueFrom:
                configMapKeyRef:
                  key: autoUpdatePipelineDefaultVersion
                  name: $(pipeline_install_configuration)
            - name: DBCONFIG_CONMAXLIFETIMESEC
              valueFrom:
                configMapKeyRef:
                  key: ConMaxLifeTimeSec
                  name: $(pipeline_install_configuration)
            - name: ML_PIPELINE_VISUALIZATIONSERVER_SERVICE_HOST
              value: ds-pipeline-visualizationserver
            - name: ML_PIPELINE_VISUALIZATIONSERVER_SERVICE_PORT
              value: "8888"
          image: api-server
          imagePullPolicy: Always
          name: ds-pipeline-api-server
          ports:
            - containerPort: 8888
              name: http
            - containerPort: 8887
              name: grpc
          livenessProbe:
            exec:
              command:
                - wget
                - -q
                - -S
                - -O
                - '-'
                - http://localhost:8888/apis/v1beta1/healthz
            initialDelaySeconds: 3
            periodSeconds: 5
            timeoutSeconds: 2
          readinessProbe:
            exec:
              command:
                - wget
                - -q
                - -S
                - -O
                - '-'
                - http://localhost:8888/apis/v1beta1/healthz
            initialDelaySeconds: 3
            periodSeconds: 5
            timeoutSeconds: 2
          resources:
            requests:
              cpu: 250m
              memory: 500Mi
            limits:
              cpu: 500m
              memory: 1Gi
      serviceAccountName: ds-pipeline
